
#check APAC_HOME Defined
ifndef APAC_HOME
    $(error APAC_HOME is undefined)
endif

NAME := Non-Constant-Class-Values
APK  := bin/$(NAME)-debug.apk

include $(APAC_HOME)/android-apps/Makefile.common
